For compression, use Zstd instead of Zlib
Zstd is significantly faster, yet gives similar compression ratio.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -979,7 +979,7 @@ enable_function_sections
 enable_mmap_map_stack
 with_afl
 with_flexdll
-with_zlib
+with_zstd
 enable_shared
 enable_static
 with_pic
@@ -1682,7 +1682,7 @@ Optional Packages:
   --with-target-bindir    location of binary programs on target system
   --with-afl              use the AFL fuzzer
   --with-flexdll          bootstrap FlexDLL from the given sources
-  --without-zlib          disable compression of marshaled data
+  --without-zstd          disable compression of marshaled data
   --with-pic[=PKGS]       try to use only PIC/non-PIC objects [default=use
                           both]
   --with-aix-soname=aix|svr4|both
@@ -3923,12 +3923,12 @@ fi
 
 
 
-# Check whether --with-zlib was given.
-if test ${with_zlib+y}
+# Check whether --with-zstd was given.
+if test ${with_zstd+y}
 then :
-  withval=$with_zlib;
+  withval=$with_zstd;
 else $as_nop
-  with_zlib=yes
+  with_zstd=yes
 fi
 
 
@@ -17985,19 +17985,19 @@ rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
 
-## Zlib compression library
+## ZSTD compression library
 
-if test x"$with_zlib" = "xyes"
+if test x"$with_zstd" = "xyes"
 then :
-  if zlib_libs=`pkg-config --libs zlib 2>/dev/null` && zlib_flags=`pkg-config --cflags zlib 2>/dev/null`
+  if zstd_libs=`pkg-config --libs libzstd 2>/dev/null` && zstd_flags=`pkg-config --cflags libzstd 2>/dev/null`
 then :
-  cclibs="$cclibs $zlib_libs"
-     internal_cppflags="$internal_cppflags $zlib_flags"
-     printf "%s\n" "#define HAS_ZLIB 1" >>confdefs.h
+  cclibs="$cclibs $zstd_libs"
+     internal_cppflags="$internal_cppflags $zstd_flags"
+     printf "%s\n" "#define HAS_ZSTD 1" >>confdefs.h
 
 else $as_nop
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: zlib not found: compressed marshaling support disabled." >&5
-printf "%s\n" "$as_me: WARNING: zlib not found: compressed marshaling support disabled." >&2;}
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: zstd not found: compressed marshaling support disabled." >&5
+printf "%s\n" "$as_me: WARNING: zstd not found: compressed marshaling support disabled." >&2;}
 fi
 fi
 
